language: python
python:
    - "3.7"
cache:
    yarn: true
    pip: true
    directories:
        - node_modules
install:
    - pip install poetry
    - poetry install
script:
    - poetry run pytest
after_script:
    - nvm install 10.16.0
    - nvm use 10.16.0
    - yarn global add danger
    - poetry run danger-python ci
